{
//////////////////////////////////////////////////////////
//   This file has been automatically generated 
//     (Wed Feb 23 20:06:41 2022 by ROOT version6.24/06)
//   from TTree kk/tree of KkAna
//   found on file: AllKKAna.root
//////////////////////////////////////////////////////////


//Reset ROOT and connect tree file
   gROOT->Reset();
   TFile *f = (TFile*)gROOT->GetListOfFiles()->FindObject("AllKKAna.root");
   if (!f) {
      f = new TFile("AllKKAna.root");
   }
    f->GetObject("kk",tree);

//Declaration of leaves types
   Int_t           runnum;
   Int_t           evnum;
   Int_t           spill;
   Int_t           trigpat[32];
   Int_t           trigflag[32];
   Int_t           nhBh1;
   Int_t           csBh1[5];
   Double_t        Bh1Seg[5];
   Double_t        tBh1[5];
   Double_t        dtBh1[5];
   Double_t        deBh1[5];
   Int_t           nhBh2;
   Int_t           csBh2[11];
   Double_t        Bh2Seg[11];
   Double_t        tBh2[11];
   Double_t        t0Bh2[11];
   Double_t        dtBh2[11];
   Double_t        deBh2[11];
   Double_t        Time0Seg;
   Double_t        deTime0;
   Double_t        Time0;
   Double_t        CTime0;
   Double_t        Btof0Seg;
   Double_t        deBtof0;
   Double_t        Btof0;
   Double_t        CBtof0;
   Int_t           nhTof;
   Int_t           csTof[26];
   Double_t        TofSeg[26];
   Double_t        tTof[26];
   Double_t        dtTof[26];
   Double_t        deTof[26];
   Int_t           nhBvh;
   Double_t        BvhSeg[8];
   Int_t           nhBft;
   Int_t           csBft[28];
   Double_t        tBft[28];
   Double_t        wBft[28];
   Double_t        BftPos[28];
   Double_t        BftSeg[28];
   Int_t           nhSch;
   Int_t           csSch[36];
   Double_t        tSch[36];
   Double_t        wSch[36];
   Double_t        SchPos[36];
   Double_t        SchSeg[36];
   Int_t           nlBcOut;
   Int_t           ntBcOut;
   Int_t           nhBcOut[4];
   Double_t        chisqrBcOut[4];
   Double_t        x0BcOut[4];
   Double_t        y0BcOut[4];
   Double_t        u0BcOut[4];
   Double_t        v0BcOut[4];
   Double_t        xtgtBcOut[4];
   Double_t        ytgtBcOut[4];
   Double_t        xbh2BcOut[4];
   Double_t        ybh2BcOut[4];
   Int_t           ntK18;
   Int_t           nhK18[4];
   Double_t        chisqrK18[4];
   Double_t        pK18[4];
   Double_t        xtgtK18[4];
   Double_t        ytgtK18[4];
   Double_t        utgtK18[4];
   Double_t        vtgtK18[4];
   Double_t        thetaK18[4];
   Int_t           nlSdcIn;
   Int_t           ntSdcIn;
   Int_t           nhSdcIn[8];
   Double_t        chisqrSdcIn[8];
   Double_t        x0SdcIn[8];
   Double_t        y0SdcIn[8];
   Double_t        u0SdcIn[8];
   Double_t        v0SdcIn[8];
   Int_t           nlSdcOut;
   Int_t           ntSdcOut;
   Int_t           nhSdcOut[8];
   Double_t        chisqrSdcOut[8];
   Double_t        x0SdcOut[8];
   Double_t        y0SdcOut[8];
   Double_t        u0SdcOut[8];
   Double_t        v0SdcOut[8];
   Int_t           ntKurama;
   Int_t           nhKurama[16];
   Double_t        chisqrKurama[16];
   Double_t        stof[16];
   Double_t        cstof[16];
   Double_t        path[16];
   Double_t        pKurama[16];
   Double_t        qKurama[16];
   Double_t        m2[16];
   Double_t        xtgtKurama[16];
   Double_t        ytgtKurama[16];
   Double_t        utgtKurama[16];
   Double_t        vtgtKurama[16];
   Double_t        thetaKurama[16];
   Double_t        xtofKurama[16];
   Double_t        ytofKurama[16];
   Double_t        utofKurama[16];
   Double_t        vtofKurama[16];
   Double_t        tofsegKurama[16];
   Double_t        best_deTof[16];
   Double_t        best_TofSeg[16];
   Int_t           nKm;
   Int_t           nKp;
   Int_t           nKK;
   Double_t        vtx[27];
   Double_t        vty[27];
   Double_t        vtz[27];
   Double_t        closeDist[27];
   Int_t           inside[27];
   Double_t        theta[27];
   Double_t        MissMass[27];
   Double_t        MissMassCorr[27];
   Double_t        MissMassCorrDE[27];
   Double_t        thetaCM[27];
   Double_t        costCM[27];
   Int_t           Kflag[27];
   Double_t        xkm[27];
   Double_t        ykm[27];
   Double_t        ukm[27];
   Double_t        vkm[27];
   Double_t        xkp[27];
   Double_t        ykp[27];
   Double_t        ukp[27];
   Double_t        vkp[27];
   Double_t        pOrg[27];
   Double_t        pCalc[27];
   Double_t        pCorr[27];
   Double_t        pCorrDE[27];

   // Set branch addresses.
   kk->SetBranchAddress("runnum",&runnum);
   kk->SetBranchAddress("evnum",&evnum);
   kk->SetBranchAddress("spill",&spill);
   kk->SetBranchAddress("trigpat",trigpat);
   kk->SetBranchAddress("trigflag",trigflag);
   kk->SetBranchAddress("nhBh1",&nhBh1);
   kk->SetBranchAddress("csBh1",csBh1);
   kk->SetBranchAddress("Bh1Seg",Bh1Seg);
   kk->SetBranchAddress("tBh1",tBh1);
   kk->SetBranchAddress("dtBh1",dtBh1);
   kk->SetBranchAddress("deBh1",deBh1);
   kk->SetBranchAddress("nhBh2",&nhBh2);
   kk->SetBranchAddress("csBh2",csBh2);
   kk->SetBranchAddress("Bh2Seg",Bh2Seg);
   kk->SetBranchAddress("tBh2",tBh2);
   kk->SetBranchAddress("t0Bh2",t0Bh2);
   kk->SetBranchAddress("dtBh2",dtBh2);
   kk->SetBranchAddress("deBh2",deBh2);
   kk->SetBranchAddress("Time0Seg",&Time0Seg);
   kk->SetBranchAddress("deTime0",&deTime0);
   kk->SetBranchAddress("Time0",&Time0);
   kk->SetBranchAddress("CTime0",&CTime0);
   kk->SetBranchAddress("Btof0Seg",&Btof0Seg);
   kk->SetBranchAddress("deBtof0",&deBtof0);
   kk->SetBranchAddress("Btof0",&Btof0);
   kk->SetBranchAddress("CBtof0",&CBtof0);
   kk->SetBranchAddress("nhTof",&nhTof);
   kk->SetBranchAddress("csTof",csTof);
   kk->SetBranchAddress("TofSeg",TofSeg);
   kk->SetBranchAddress("tTof",tTof);
   kk->SetBranchAddress("dtTof",dtTof);
   kk->SetBranchAddress("deTof",deTof);
   kk->SetBranchAddress("nhBvh",&nhBvh);
   kk->SetBranchAddress("BvhSeg",BvhSeg);
   kk->SetBranchAddress("nhBft",&nhBft);
   kk->SetBranchAddress("csBft",csBft);
   kk->SetBranchAddress("tBft",tBft);
   kk->SetBranchAddress("wBft",wBft);
   kk->SetBranchAddress("BftPos",BftPos);
   kk->SetBranchAddress("BftSeg",BftSeg);
   kk->SetBranchAddress("nhSch",&nhSch);
   kk->SetBranchAddress("csSch",csSch);
   kk->SetBranchAddress("tSch",tSch);
   kk->SetBranchAddress("wSch",wSch);
   kk->SetBranchAddress("SchPos",SchPos);
   kk->SetBranchAddress("SchSeg",SchSeg);
   kk->SetBranchAddress("nlBcOut",&nlBcOut);
   kk->SetBranchAddress("ntBcOut",&ntBcOut);
   kk->SetBranchAddress("nhBcOut",nhBcOut);
   kk->SetBranchAddress("chisqrBcOut",chisqrBcOut);
   kk->SetBranchAddress("x0BcOut",x0BcOut);
   kk->SetBranchAddress("y0BcOut",y0BcOut);
   kk->SetBranchAddress("u0BcOut",u0BcOut);
   kk->SetBranchAddress("v0BcOut",v0BcOut);
   kk->SetBranchAddress("xtgtBcOut",xtgtBcOut);
   kk->SetBranchAddress("ytgtBcOut",ytgtBcOut);
   kk->SetBranchAddress("xbh2BcOut",xbh2BcOut);
   kk->SetBranchAddress("ybh2BcOut",ybh2BcOut);
   kk->SetBranchAddress("ntK18",&ntK18);
   kk->SetBranchAddress("nhK18",nhK18);
   kk->SetBranchAddress("chisqrK18",chisqrK18);
   kk->SetBranchAddress("pK18",pK18);
   kk->SetBranchAddress("xtgtK18",xtgtK18);
   kk->SetBranchAddress("ytgtK18",ytgtK18);
   kk->SetBranchAddress("utgtK18",utgtK18);
   kk->SetBranchAddress("vtgtK18",vtgtK18);
   kk->SetBranchAddress("thetaK18",thetaK18);
   kk->SetBranchAddress("nlSdcIn",&nlSdcIn);
   kk->SetBranchAddress("ntSdcIn",&ntSdcIn);
   kk->SetBranchAddress("nhSdcIn",nhSdcIn);
   kk->SetBranchAddress("chisqrSdcIn",chisqrSdcIn);
   kk->SetBranchAddress("x0SdcIn",x0SdcIn);
   kk->SetBranchAddress("y0SdcIn",y0SdcIn);
   kk->SetBranchAddress("u0SdcIn",u0SdcIn);
   kk->SetBranchAddress("v0SdcIn",v0SdcIn);
   kk->SetBranchAddress("nlSdcOut",&nlSdcOut);
   kk->SetBranchAddress("ntSdcOut",&ntSdcOut);
   kk->SetBranchAddress("nhSdcOut",nhSdcOut);
   kk->SetBranchAddress("chisqrSdcOut",chisqrSdcOut);
   kk->SetBranchAddress("x0SdcOut",x0SdcOut);
   kk->SetBranchAddress("y0SdcOut",y0SdcOut);
   kk->SetBranchAddress("u0SdcOut",u0SdcOut);
   kk->SetBranchAddress("v0SdcOut",v0SdcOut);
   kk->SetBranchAddress("ntKurama",&ntKurama);
   kk->SetBranchAddress("nhKurama",nhKurama);
   kk->SetBranchAddress("chisqrKurama",chisqrKurama);
   kk->SetBranchAddress("stof",stof);
   kk->SetBranchAddress("cstof",cstof);
   kk->SetBranchAddress("path",path);
   kk->SetBranchAddress("pKurama",pKurama);
   kk->SetBranchAddress("qKurama",qKurama);
   kk->SetBranchAddress("m2",m2);
   kk->SetBranchAddress("xtgtKurama",xtgtKurama);
   kk->SetBranchAddress("ytgtKurama",ytgtKurama);
   kk->SetBranchAddress("utgtKurama",utgtKurama);
   kk->SetBranchAddress("vtgtKurama",vtgtKurama);
   kk->SetBranchAddress("thetaKurama",thetaKurama);
   kk->SetBranchAddress("xtofKurama",xtofKurama);
   kk->SetBranchAddress("ytofKurama",ytofKurama);
   kk->SetBranchAddress("utofKurama",utofKurama);
   kk->SetBranchAddress("vtofKurama",vtofKurama);
   kk->SetBranchAddress("tofsegKurama",tofsegKurama);
   kk->SetBranchAddress("best_deTof",best_deTof);
   kk->SetBranchAddress("best_TofSeg",best_TofSeg);
   kk->SetBranchAddress("nKm",&nKm);
   kk->SetBranchAddress("nKp",&nKp);
   kk->SetBranchAddress("nKK",&nKK);
   kk->SetBranchAddress("vtx",vtx);
   kk->SetBranchAddress("vty",vty);
   kk->SetBranchAddress("vtz",vtz);
   kk->SetBranchAddress("closeDist",closeDist);
   kk->SetBranchAddress("inside",inside);
   kk->SetBranchAddress("theta",theta);
   kk->SetBranchAddress("MissMass",MissMass);
   kk->SetBranchAddress("MissMassCorr",MissMassCorr);
   kk->SetBranchAddress("MissMassCorrDE",MissMassCorrDE);
   kk->SetBranchAddress("thetaCM",thetaCM);
   kk->SetBranchAddress("costCM",costCM);
   kk->SetBranchAddress("Kflag",Kflag);
   kk->SetBranchAddress("xkm",xkm);
   kk->SetBranchAddress("ykm",ykm);
   kk->SetBranchAddress("ukm",ukm);
   kk->SetBranchAddress("vkm",vkm);
   kk->SetBranchAddress("xkp",xkp);
   kk->SetBranchAddress("ykp",ykp);
   kk->SetBranchAddress("ukp",ukp);
   kk->SetBranchAddress("vkp",vkp);
   kk->SetBranchAddress("pOrg",pOrg);
   kk->SetBranchAddress("pCalc",pCalc);
   kk->SetBranchAddress("pCorr",pCorr);
   kk->SetBranchAddress("pCorrDE",pCorrDE);

//     This is the loop skeleton
//       To read only selected branches, Insert statements like:
// kk->SetBranchStatus("*",0);  // disable all branches
// TTreePlayer->SetBranchStatus("branchname",1);  // activate branchname

   Long64_t nentries = kk->GetEntries();

   Long64_t nbytes = 0;
//   for (Long64_t i=0; i<nentries;i++) {
//      nbytes += kk->GetEntry(i);
//   }
}
